version: '3.4'

services:
  # Servi�o do Banco de Dados (SQL Server)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: leilao_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  # Servi�o do Redis (Cache)
  redis:
    image: redis:alpine
    container_name: leilao_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sql_data:
  redis_data: